### ISSUE TITLE
Why have an Identifier class?

### ISSUE THREAD

**Issue by julesjacobsen** [GA4GH-Pedigree-Standard/pedigree-tools#8]
```proto
message Identifier {
    string id = 1; //	ID 	required 	an external identifier such as a medical record number, participant id, or insurance number;  URI/CURIE is preferred
}
```
Given this simple wraps a string, what is the point of it? Can we just replace it with a string?

**Comment by buske** [comment]
This was discussed here: https://github.com/GA4GH-Pedigree-Standard/pedigree/issues/8

**Comment by julesjacobsen** [comment]
But wrapping the string in an Identifier class still doesn't help with Michael's argument that the ID should be a CURIE. There is no format checking anywhere and no standard for an identifier anyway. So that's all nice in theory, but in practice an identifier could be anything and it's the users decision about what they want to use. It might be insane, but that's not for us to judge as its simply a label from the perspective of the pedigree.
